'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowLeftIcon, ArrowRightIcon, CheckIcon, ClipboardDocumentIcon, DocumentArrowUpIcon, SparklesIcon, WrenchScrewdriverIcon } from '@heroicons/react/24/outline'

type Choice = 'widget' | 'import'
type Site = { id: string; name: string | null; url: string }

export default function OnboardingPage() {
  const router = useRouter()
  const queryClient = useQueryClient()
  const [choice, setChoice] = useState<Choice | null>(null)
  const [projectName, setProjectName] = useState('')
  const [projectUrl, setProjectUrl] = useState('')
  const [site, setSite] = useState<Site | null>(null)
  const [widgetKey, setWidgetKey] = useState<string | null>(null)
  const [csvFile, setCsvFile] = useState<File | null>(null)
  const [status, setStatus] = useState<string | null>(null)
  const [busy, setBusy] = useState(false)
  const { data: sites } = useQuery({ queryKey: ['sites'], queryFn: async () => { const response = await fetch('/api/sites'); if (!response.ok) throw new Error(); return response.json() as Promise<Site[]> } })

  async function createProject(event: React.FormEvent) {
    event.preventDefault(); setStatus(null); if (!projectUrl.trim()) return setStatus('Ajoutez l’URL de votre site pour créer votre projet.'); setBusy(true)
    try { const response = await fetch('/api/sites', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url: projectUrl, name: projectName || undefined }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setSite(result); await queryClient.invalidateQueries({ queryKey: ['sites'] }); setStatus(null) } catch (error) { setStatus(error instanceof Error ? error.message : 'Impossible de créer le projet.') } finally { setBusy(false) }
  }

  async function prepareWidget() { const target = site ?? sites?.[0]; if (!target) return setStatus('Créez d’abord votre projet.'); setBusy(true); const response = await fetch('/api/feedback/sources', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ siteId: target.id }) }); const result = await response.json(); setBusy(false); if (!response.ok) return setStatus(result.error ?? 'Impossible de préparer le widget.'); setSite(target); setWidgetKey(result.public_key) }
  async function importCsv() { const target = site ?? sites?.[0]; if (!target || !csvFile) return setStatus('Sélectionnez un projet et un fichier CSV.'); setBusy(true); const text = await csvFile.text(); const response = await fetch('/api/feedback/import', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ siteId: target.id, csv: text }) }); const result = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) return setStatus(result.error ?? 'Impossible d’importer ce fichier.'); setStatus(`${result.imported} avis importés. ${result.skipped} ligne(s) ignorée(s).`); setSite(target) }
  const activeSite = site ?? sites?.[0]
  const step = !activeSite ? 1 : !choice ? 2 : 3

  return <main className="min-h-screen bg-[#fbfbfb] px-5 py-8 text-gray-950 dark:bg-[#0b0c0e] dark:text-white sm:px-8"><div className="mx-auto max-w-5xl"><header className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-gray-950 p-1.5 dark:bg-black"><img src="/qualio-logo/export/mark/monogram-orange.svg" alt="Qualio" className="h-full w-full" /></div><div><strong className="block text-sm">Qualio</strong><span className="font-mono text-[9px] uppercase tracking-[0.12em] text-gray-400">Première configuration</span></div></div><button type="button" onClick={() => router.push('/dashboard')} className="text-xs font-semibold text-gray-500 hover:text-gray-900 dark:text-zinc-400 dark:hover:text-white">Passer pour l’instant</button></header><div className="mx-auto mt-16 max-w-3xl"><div className="mb-8 flex items-center gap-2">{[1, 2, 3].map((item) => <div key={item} className={`h-1.5 flex-1 rounded-full ${item <= step ? 'bg-[#ee6018]' : 'bg-gray-200 dark:bg-white/10'}`} />)}</div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#c95720]">Étape {step} sur 3</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.05em] text-gray-950 dark:text-white">{!activeSite ? 'Créons votre espace.' : !choice ? 'Comment voulez-vous commencer ?' : choice === 'widget' ? 'Ajoutez les nouveaux avis.' : 'Rassemblez vos avis existants.'}</h1><p className="mt-3 max-w-2xl text-base leading-7 text-gray-500 dark:text-zinc-400">{!activeSite ? 'Un projet correspond à votre produit ou votre site. Il sert uniquement à regrouper vos avis et vos sources.' : !choice ? 'Vous pourrez toujours ajouter l’autre source plus tard. L’important est de commencer avec ce que vous avez déjà.' : choice === 'widget' ? 'Copiez un petit script sur votre site. Les prochains avis arriveront ensuite automatiquement dans Qualio.' : 'Importez un fichier CSV pour commencer avec votre historique. Qualio le structurera avant de produire une synthèse.'}</p>{status && <p className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900 dark:border-amber-500/20 dark:bg-amber-500/10 dark:text-amber-200">{status}</p>}

{!activeSite && <form onSubmit={createProject} className="mt-10 rounded-2xl border border-gray-200 bg-white p-6 shadow-[0_12px_40px_rgba(17,24,39,.06)] dark:border-white/[0.08] dark:bg-[#16181e]"><label className="block text-xs font-semibold text-gray-700 dark:text-zinc-300">Nom du projet (facultatif)<input value={projectName} onChange={(event) => setProjectName(event.target.value)} placeholder="Mon produit" className="mt-2 w-full rounded-xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm outline-none focus:border-[#ee6018] dark:border-white/10 dark:bg-white/[0.04] dark:text-white" /></label><label className="mt-4 block text-xs font-semibold text-gray-700 dark:text-zinc-300">URL du site<input value={projectUrl} onChange={(event) => setProjectUrl(event.target.value)} type="url" required placeholder="https://mon-site.com" className="mt-2 w-full rounded-xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm outline-none focus:border-[#ee6018] dark:border-white/10 dark:bg-white/[0.04] dark:text-white" /></label><button disabled={busy} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#ee6018] px-4 py-3 text-sm font-bold text-white disabled:opacity-60">{busy ? 'Création…' : 'Continuer'}<ArrowRightIcon className="h-4 w-4" /></button></form>}

{activeSite && !choice && <div className="mt-10 grid gap-4 md:grid-cols-2"><ChoiceCard icon={<WrenchScrewdriverIcon />} title="Installer le widget" body="Pour recevoir les nouveaux avis directement sur votre site." onClick={() => setChoice('widget')} /><ChoiceCard icon={<DocumentArrowUpIcon />} title="Importer mes avis" body="Pour commencer avec les avis que vous avez déjà reçus." onClick={() => setChoice('import')} /></div>}

{activeSite && choice === 'widget' && !widgetKey && <div className="mt-10 rounded-2xl border border-gray-200 bg-white p-6 dark:border-white/[0.08] dark:bg-[#16181e]"><div className="flex items-start gap-4"><div className="rounded-xl bg-orange-50 p-3 text-[#ee6018] dark:bg-orange-500/10"><SparklesIcon className="h-5 w-5" /></div><div><h2 className="text-lg font-semibold">Préparer votre widget</h2><p className="mt-1 text-sm leading-6 text-gray-500 dark:text-zinc-400">Qualio va créer une source sécurisée pour votre projet. Vous recevrez ensuite le script prêt à copier.</p></div></div><button onClick={prepareWidget} disabled={busy} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#ee6018] px-4 py-3 text-sm font-bold text-white disabled:opacity-60">{busy ? 'Préparation…' : 'Générer mon script'}<ArrowRightIcon className="h-4 w-4" /></button></div>}
{activeSite && choice === 'widget' && widgetKey && <div className="mt-10 rounded-2xl border border-gray-200 bg-white p-6 dark:border-white/[0.08] dark:bg-[#16181e]"><div className="flex items-center gap-2 text-sm font-semibold text-emerald-700 dark:text-emerald-300"><CheckIcon className="h-5 w-5" />Source widget prête</div><p className="mt-3 text-sm leading-6 text-gray-500 dark:text-zinc-400">Collez ce script juste avant la balise <code>&lt;/body&gt;</code> de votre site.</p><div className="mt-4 overflow-x-auto rounded-xl bg-gray-950 p-4 font-mono text-xs leading-6 text-gray-200">{`<script src="${typeof window !== 'undefined' ? window.location.origin : ''}/widget.js" data-key="${widgetKey}"></script>`}</div><button onClick={() => navigator.clipboard?.writeText(`<script src="${window.location.origin}/widget.js" data-key="${widgetKey}"></script>`)} className="mt-4 inline-flex items-center gap-2 rounded-xl border border-gray-200 px-4 py-2.5 text-xs font-bold hover:border-gray-400 dark:border-white/10"><ClipboardDocumentIcon className="h-4 w-4" />Copier le script</button><button onClick={() => router.push('/dashboard')} className="ml-3 inline-flex items-center gap-2 rounded-xl bg-gray-950 px-4 py-2.5 text-xs font-bold text-white dark:bg-white dark:text-gray-950">Ouvrir mon espace<ArrowRightIcon className="h-4 w-4" /></button></div>}
{activeSite && choice === 'import' && <div className="mt-10 rounded-2xl border border-gray-200 bg-white p-6 dark:border-white/[0.08] dark:bg-[#16181e]"><label className="flex min-h-44 cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-gray-300 bg-gray-50 px-5 text-center dark:border-white/10 dark:bg-white/[0.03]"><DocumentArrowUpIcon className="h-7 w-7 text-gray-400" /><span className="mt-3 text-sm font-semibold">Choisir un fichier CSV</span><span className="mt-1 text-xs text-gray-500">Une colonne `content` est nécessaire.</span><input type="file" accept=".csv,text/csv" onChange={(event) => setCsvFile(event.target.files?.[0] ?? null)} className="sr-only" /></label>{csvFile && <p className="mt-3 text-xs text-gray-500">{csvFile.name}</p>}<button onClick={importCsv} disabled={busy || !csvFile} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#ee6018] px-4 py-3 text-sm font-bold text-white disabled:opacity-50">{busy ? 'Import…' : 'Importer les avis'}<ArrowRightIcon className="h-4 w-4" /></button>{status?.includes('importés') && <button onClick={() => router.push('/dashboard')} className="ml-3 inline-flex items-center gap-2 rounded-xl border border-gray-200 px-4 py-3 text-sm font-bold dark:border-white/10">Ouvrir mon espace<ArrowRightIcon className="h-4 w-4" /></button>}</div>}
</div></div></main>
}

function ChoiceCard({ icon, title, body, onClick }: { icon: React.ReactNode; title: string; body: string; onClick: () => void }) { return <button type="button" onClick={onClick} className="group rounded-2xl border border-gray-200 bg-white p-6 text-left transition hover:-translate-y-0.5 hover:border-[#ee6018]/50 hover:shadow-[0_16px_40px_rgba(17,24,39,.08)] dark:border-white/[0.08] dark:bg-[#16181e]"><span className="inline-flex rounded-xl bg-orange-50 p-3 text-[#ee6018] dark:bg-orange-500/10">{icon}</span><h2 className="mt-5 text-lg font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-gray-500 dark:text-zinc-400">{body}</p><span className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-[#c95720]">Commencer<ArrowRightIcon className="h-4 w-4 transition group-hover:translate-x-1" /></span></button> }
