'use client'
import Link from 'next/link'
import { useParams } from 'next/navigation'
import { useEffect, useRef, useState } from 'react'
import type { MouseEvent } from 'react'
import { ArrowLeftIcon, ArrowPathIcon } from '@heroicons/react/24/outline'
import { useScanStatus } from '@/lib/hooks/useScan'
import { ScanProgressPanel } from '@/components/dashboard/ScanProgressPanel'
const TERMINAL = ['completed', 'failed', 'partial', 'blocked']
export default function ScanProgressPage() {
  const { scanId } = useParams<{ scanId: string }>(); const { data: scan, isLoading, isError, refetch } = useScanStatus(scanId); const isActive = Boolean(scan && !TERMINAL.includes(scan.status)); const [isRetrying, setIsRetrying] = useState(false); const [retryError, setRetryError] = useState<string | null>(null); const autoStartAttempted = useRef(false)
  const leaveProgress = (event: MouseEvent<HTMLAnchorElement>) => { if (isActive && !window.confirm('Le scan est encore en cours. Vous pourrez le retrouver dans l’historique. Continuer ?')) event.preventDefault() }
  const retryWorker = async () => { setIsRetrying(true); setRetryError(null); try { const response = await fetch('/api/scan/run', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ scanId }) }); const responseText = await response.text(); let payload: { error?: string } = {}; try { payload = JSON.parse(responseText) as { error?: string } } catch { /* plain text */ } if (!response.ok) throw new Error(payload.error || responseText || `Le worker a répondu avec le statut ${response.status}.`); await refetch() } catch (error) { setRetryError(error instanceof Error ? error.message : 'Le worker n’a pas pu démarrer.') } finally { setIsRetrying(false) } }
  useEffect(() => { if (!isActive) return; const warnBeforeLeaving = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = 'Votre scan est encore en cours. Voulez-vous vraiment quitter cette page ?' }; window.addEventListener('beforeunload', warnBeforeLeaving); return () => window.removeEventListener('beforeunload', warnBeforeLeaving) }, [isActive])
  useEffect(() => { if (scan?.status !== 'queued' || autoStartAttempted.current) return; autoStartAttempted.current = true; void retryWorker() }, [scan?.status])
  if (isLoading) return <div className="py-16 text-center text-sm text-gray-500">Chargement du suivi du scan…</div>
  if (isError || !scan) return <div className="py-16 text-center text-sm text-red-500">Impossible de charger ce scan.</div>
  return <div className="mx-auto max-w-3xl space-y-6 pb-16"><Link href="/dashboard/scans" onClick={leaveProgress} className="inline-flex items-center gap-2 text-xs font-semibold text-gray-500 hover:text-gray-900 dark:text-zinc-400 dark:hover:text-white"><ArrowLeftIcon className="h-4 w-4" /> Retour à l’historique</Link><section className="rounded-2xl border border-gray-200/80 bg-white p-6 dark:border-white/[0.08] dark:bg-[#16181E]"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#ee6018]">Suivi du scan</p><h1 className="mt-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{scan.status === 'queued' ? 'Votre scan attend son exécution' : scan.status === 'completed' ? 'Votre rapport est prêt' : scan.status === 'failed' || scan.status === 'blocked' ? 'Le scan a rencontré un problème' : 'Qualio travaille sur votre site'}</h1><p className="mt-2 text-sm text-gray-500 dark:text-zinc-400">Session <span className="font-mono">{scanId.slice(0, 12)}</span> · {scan.status}</p></div><div className="text-left sm:text-right"><p className="text-3xl font-bold tabular-nums text-gray-900 dark:text-white">{scan.progress}%</p><p className="text-xs text-gray-500 dark:text-zinc-400">{scan.pagesDiscovered ?? 0} pages découvertes</p></div></div></section><section className="rounded-2xl border border-gray-200/80 bg-white p-6 dark:border-white/[0.08] dark:bg-[#16181E]"><div className="mb-5 flex items-center justify-between"><h2 className="text-sm font-bold text-gray-900 dark:text-white">{scan.status === 'queued' ? 'En attente du worker' : 'Ce qui se passe maintenant'}</h2><span className="text-xs text-gray-500 dark:text-zinc-400">Mise à jour automatique</span></div>{scan.status === 'queued' && <div className="mb-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800">Le scan est enregistré. Qualio démarre automatiquement l’exécution.</div>}<ScanProgressPanel scanId={scanId} variant="full" />{scan.status === 'queued' && retryError && <div className="mt-5 flex flex-wrap items-center gap-3"><button type="button" onClick={retryWorker} disabled={isRetrying} className="inline-flex items-center gap-2 rounded-lg bg-[#ee6018] px-4 py-2 text-xs font-semibold text-white disabled:opacity-60"><ArrowPathIcon className={`h-3.5 w-3.5 ${isRetrying ? 'animate-spin' : ''}`} />{isRetrying ? 'Démarrage du worker…' : 'Réessayer l’exécution'}</button><span className="text-xs text-red-600">{retryError}</span></div>}</section></div>
}
