"use client";

import { motion } from "framer-motion";
import { Navbar } from "@/components/landing/Navbar";
import { Footer } from "@/components/landing/Footer";
import { useLanguage } from "@/context/LanguageContext";

const C = { bg: "#000", surface: "#141414", border: "rgba(255,255,255,.08)", text: "#eee", muted: "#8a8380", orange: "#ee6018", green: "#a0ca92" };
type PageKind = "product" | "resources" | "pricing" | "contact" | "solutions";
type Card = readonly [string, string, string, string?];
type Detail = { title: string; intro: string; columns: readonly { title: string; items: readonly string[] }[] };

const pages = {
  en: {
    product: { title: "Website QA that shows its work.", intro: "Qualio runs real browser journeys against your site, captures the evidence around each failure, and turns it into a diagnosis your team can act on.", sections: [["scans", "Live browser scans", "Qualio opens your site in a Playwright Chromium session. It follows reachable pages, clicks buttons, tests forms, checks links, and observes the network and console as a real visitor would."], ["evidence", "Evidence before diagnosis", "Every issue keeps the context needed to reproduce it: a screenshot, network requests, console output, DOM state, impact, reproduction steps, and a confidence level for the likely cause."], ["history", "A QA history you can verify", "After a fix, run the same workspace again. Qualio compares the new result with the previous scan so resolved issues and new regressions stay visible over time."]] as Card[] },
    resources: { title: "Understand what Qualio checks.", intro: "Short explanations of what gets tested, which evidence is collected, and how to move from a detected problem to a verified correction.", sections: [["how-it-works", "From URL to correction prompt", "Add a URL, choose the environment and scan depth. Playwright runs the journeys, Qualio gathers the evidence, then AI describes impact, likely cause, and reproduction steps. Copy the prompt, fix the issue, and run the scan again."], ["detects", "What Qualio detects", "Dead clicks, broken CTAs, forms that fail to submit, 404/500 links, JavaScript errors, failed network requests, and responsive problems: Qualio focuses on failures a user can actually encounter."], ["docs", "Product documentation", "Qualio works from outside your codebase: a URL is enough, with no SDK or instrumentation required. Production, Staging, and Preview environments can keep their own scan history."]] as Card[] },
  },
  fr: {
    product: { title: "La QA web qui montre ses preuves.", intro: "Qualio lance de vrais parcours navigateur sur votre site, conserve les preuves autour de chaque problème et les transforme en diagnostic exploitable par votre équipe.", sections: [["scans", "Des scans dans un vrai navigateur", "Qualio ouvre votre site dans une session Playwright Chromium. Il explore les pages accessibles, clique sur les boutons, teste les formulaires, vérifie les liens et observe le réseau et la console comme un vrai visiteur."], ["evidence", "Les preuves avant le diagnostic", "Chaque problème conserve le contexte nécessaire pour le reproduire : capture d’écran, requêtes réseau, sortie console, état du DOM, impact, étapes de reproduction et niveau de confiance sur la cause probable."], ["history", "Un historique QA vérifiable", "Après une correction, relancez le même espace. Qualio compare le nouveau résultat au scan précédent pour garder visibles les problèmes résolus et les nouvelles régressions."]] as Card[] },
    resources: { title: "Comprendre ce que Qualio vérifie.", intro: "Des explications courtes pour savoir ce qui est testé, quelles preuves sont collectées et comment passer d’un problème détecté à une correction vérifiée.", sections: [["how-it-works", "De l’URL au prompt de correction", "Ajoutez une URL, choisissez l’environnement et la profondeur du scan. Playwright exécute les parcours, Qualio rassemble les preuves, puis l’IA décrit l’impact, la cause probable et les étapes de reproduction. Vous copiez le prompt, corrigez, puis relancez le scan."], ["detects", "Ce que Qualio détecte", "Clics morts, CTA cassés, formulaires qui ne s’envoient pas, liens 404/500, erreurs JavaScript, requêtes réseau en échec et problèmes responsive : Qualio se concentre sur les défaillances qu’un utilisateur peut réellement rencontrer."], ["docs", "Documentation produit", "Le produit fonctionne depuis l’extérieur de votre codebase : une URL suffit, aucun SDK ni instrumentation n’est requis. Les environnements Production, Staging et Preview peuvent conserver leur propre historique."]] as Card[] },
  },
} as const;

export function MarketingPage({ kind }: { kind: PageKind }) {
  const { language } = useLanguage();
  const isFr = language === "fr";
  const page = pages[language][kind === "product" ? "product" : "resources"];
  const pricing = isFr ? { title: "Un accès anticipé pour tester le parcours complet.", intro: "Créez votre compte, ajoutez un site, lancez un scan, inspectez les preuves et copiez le prompt de correction. Les tarifs seront annoncés avant l’activation des offres payantes.", action: "Créer mon compte", note: "Aucune carte bancaire requise pendant l’accès anticipé." } : { title: "Early access to the complete QA flow.", intro: "Create an account, add a site, run a scan, inspect the evidence, and copy the generated correction prompt. Pricing will be announced before paid plans launch.", action: "Create my account", note: "No credit card required during early access." };
  const contact = isFr ? { title: "Parler à l’équipe Qualio.", intro: "Une question sur un scan, l’accès anticipé ou la façon dont Qualio observe votre site ? Écrivez-nous et décrivez le parcours que vous voulez protéger.", sales: "Questions produit", salesBody: "Pour comprendre le fonctionnement, préparer un premier scan ou discuter de votre cas d’usage.", email: "hello@qualio.dev", action: "Écrire à l’équipe" } : { title: "Talk to the Qualio team.", intro: "Questions about a scan, early access, or how Qualio observes your site? Tell us which journey you want to protect and we’ll help you get started.", sales: "Product questions", salesBody: "Understand the workflow, prepare a first scan, or talk through the journey you need to protect.", email: "hello@qualio.dev", action: "Email the team" };
  const solutionCopy = getSolutions(language);
  const detail = getDetail(kind, language);
  const cards = kind === "solutions" ? solutionCopy.cards : page.sections;
  const title = kind === "solutions" ? solutionCopy.title : page.title;
  const intro = kind === "solutions" ? solutionCopy.intro : page.intro;

  return <div className="landing-page" style={{ minHeight: "100vh", background: C.bg, color: C.text }}><Navbar /><main style={{ maxWidth: 1200, margin: "0 auto", padding: "170px 24px 120px" }}>
    {kind === "pricing" ? <><Hero title={pricing.title} intro={pricing.intro} /><section className="marketing-two-col" style={{ marginTop: 72, display: "grid", gridTemplateColumns: "minmax(0,1.1fr) minmax(280px,.9fr)", gap: 16 }}><div style={{ padding: 32, border: `1px solid ${C.border}`, borderRadius: 12, background: C.surface }}><div style={{ color: C.orange, fontFamily: "var(--font-jetbrains-mono)", fontSize: 11, textTransform: "uppercase", letterSpacing: ".1em", marginBottom: 18 }}>Early access</div><h2 style={{ fontSize: 28, fontWeight: 500, margin: 0 }}>{isFr ? "Accès anticipé Qualio" : "Qualio early access"}</h2><p style={{ color: C.muted, lineHeight: 1.7, maxWidth: 520 }}>{pricing.intro}</p><a href="/login?mode=register" style={{ display: "inline-flex", marginTop: 20, padding: "12px 18px", borderRadius: 7, background: C.text, color: C.bg, textDecoration: "none", fontWeight: 600 }}>{pricing.action} →</a></div><div style={{ padding: 32, border: `1px solid ${C.border}`, borderRadius: 12 }}><div style={{ color: C.green, fontFamily: "var(--font-jetbrains-mono)", fontSize: 11, textTransform: "uppercase", letterSpacing: ".1em", marginBottom: 18 }}>Access</div><p style={{ fontSize: 22, margin: 0, fontWeight: 500 }}>{isFr ? "Gratuit pendant l’accès anticipé" : "Free during early access"}</p><p style={{ color: C.muted, lineHeight: 1.7 }}>{pricing.note}</p></div></section></> : kind === "contact" ? <><Hero title={contact.title} intro={contact.intro} /><section className="marketing-two-col" style={{ marginTop: 72, display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: 16 }}><ContactCard title={contact.sales} body={contact.salesBody} href={`mailto:${contact.email}`} action={contact.action} /><ContactCard title="Support" body={isFr ? "Signaler un problème ou partager un retour sur le produit." : "Report a problem or share feedback about the product."} href={`mailto:${contact.email}`} action={contact.email} /></section></> : <><Hero title={title} intro={intro} /><section className="marketing-three-col" style={{ marginTop: 72, display: "grid", gridTemplateColumns: "repeat(3,minmax(0,1fr))", gap: 16 }}>{cards.map(([id, cardTitle, body, href]) => <motion.article key={id} id={id} initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-50px" }} transition={{ duration: .45 }} style={{ minHeight: 300, padding: 28, border: `1px solid ${C.border}`, borderRadius: 12, background: C.surface, display: "flex", flexDirection: "column" }}><h2 style={{ fontSize: 22, fontWeight: 500, lineHeight: 1.2, margin: "0 0 24px" }}>{cardTitle}</h2><p style={{ color: C.muted, lineHeight: 1.75, margin: 0 }}>{body}</p>{kind === "solutions" && <a href={href ?? `#${id}`} style={{ color: C.text, textDecoration: "none", fontSize: 13, marginTop: "auto", paddingTop: 28 }}>{isFr ? "Explorer" : "Explore"} →</a>}</motion.article>)}</section><DetailSection title={detail.title} intro={detail.intro} columns={detail.columns} /></>}
  </main><Footer /></div>;
}

function getSolutions(language: "en" | "fr") {
  return language === "fr" ? { title: "Une QA adaptée à votre façon de livrer.", intro: "Qualio protège les parcours qui comptent, du premier scan sur un site en production à la vérification d’une correction sur un environnement de staging.", cards: [["production", "Site en production", "Vérifiez les liens, CTA, formulaires et erreurs visibles après une mise en ligne.", "/product#scans"], ["staging", "Staging et preview", "Testez une version avant de la publier et comparez les résultats après chaque correction.", "/product#history"], ["team", "Équipe produit", "Partagez des preuves et des étapes de reproduction que chacun peut comprendre.", "/product#evidence"]] as Card[] } : { title: "QA that fits the way you ship.", intro: "Qualio protects the journeys that matter, from a first scan on production to verifying a fix in staging.", cards: [["production", "Production websites", "Check links, CTAs, forms, and visible errors after a release.", "/product#scans"], ["staging", "Staging and preview", "Test a version before release and compare results after each fix.", "/product#history"], ["team", "Product teams", "Share evidence and reproduction steps everyone can understand.", "/product#evidence"]] as Card[] };
}

function getDetail(kind: PageKind, language: "en" | "fr"): Detail {
  const product = kind === "product" || kind === "solutions";
  if (language === "fr") return product ? { title: "Un scan Qualio suit un chemin précis.", intro: "Chaque étape répond à une question concrète : le parcours fonctionne-t-il, que s’est-il passé et que faut-il corriger ?", columns: [{ title: "Avant le scan", items: ["Ajoutez l’URL du site à tester", "Choisissez Production, Staging ou Preview", "Sélectionnez Rapide, Standard ou Complet"] }, { title: "Pendant le scan", items: ["Le navigateur ouvre les pages accessibles", "Les clics, formulaires et liens sont exercés", "Les captures, requêtes et erreurs console sont conservées"] }, { title: "Après le scan", items: ["Chaque problème reçoit un impact et une cause probable", "Le niveau de confiance et les étapes de reproduction restent visibles", "Le prompt de correction peut être copié puis vérifié par un re-scan"] }] } : { title: "A Qualio scan follows a clear path.", intro: "Every step answers a practical question: does the journey work, what happened, and what should the team fix?", columns: [{ title: "Before the scan", items: ["Add the site URL you want to test", "Choose Production, Staging, or Preview", "Select Quick, Standard, or Full depth"] }, { title: "During the scan", items: ["The browser opens reachable pages", "Clicks, forms, and links are exercised", "Screenshots, requests, and console errors are captured"] }, { title: "After the scan", items: ["Each issue gets impact and a likely cause", "Confidence and reproduction steps stay visible", "Copy the correction prompt, then verify it with a re-scan"] }] };
  return { title: "A resource should move the work forward.", intro: "Start with the journey you want to protect, then use the resources to understand the evidence and choose the next action.", columns: [{ title: "Understand the flow", items: ["A URL starts a real browser session", "Scan depth sets the scope of exploration", "History lets you compare deployments"] }, { title: "Read the evidence", items: ["The screenshot shows the failing step", "Network and console output provide technical context", "Impact translates the error into a user consequence"] }, { title: "Take action", items: ["Copy the reproduction steps", "Use the prompt in your coding assistant", "Run another scan to confirm the fix"] }] };
}

function Hero({ title, intro }: { title: string; intro: string }) { return <div style={{ maxWidth: 760 }}><h1 style={{ margin: 0, fontSize: "clamp(48px,7vw,86px)", lineHeight: .98, letterSpacing: "-.055em", fontWeight: 500 }}>{title}</h1><p style={{ margin: "32px 0 0", maxWidth: 620, color: C.muted, fontSize: 19, lineHeight: 1.65 }}>{intro}</p></div>; }
function ContactCard({ title, body, href, action }: { title: string; body: string; href: string; action: string }) { return <article style={{ minHeight: 280, padding: 30, border: `1px solid ${C.border}`, borderRadius: 12, background: C.surface, display: "flex", flexDirection: "column" }}><h2 style={{ fontSize: 24, fontWeight: 500, margin: 0 }}>{title}</h2><p style={{ marginTop: "auto", color: C.muted, lineHeight: 1.7 }}>{body}</p><a href={href} style={{ color: C.text, textDecoration: "none", fontSize: 14 }}>{action} →</a></article>; }
function DetailSection({ title, intro, columns }: Detail) { return <section style={{ marginTop: 96, paddingTop: 72, borderTop: `1px solid ${C.border}` }}><div style={{ maxWidth: 680 }}><h2 style={{ fontSize: "clamp(30px,4vw,50px)", lineHeight: 1.05, letterSpacing: "-.04em", fontWeight: 500, margin: 0 }}>{title}</h2><p style={{ color: C.muted, lineHeight: 1.7, fontSize: 16, margin: "24px 0 0" }}>{intro}</p></div><div className="marketing-three-col" style={{ display: "grid", gridTemplateColumns: "repeat(3,minmax(0,1fr))", gap: 16, marginTop: 48 }}>{columns.map(column => <div key={column.title} style={{ paddingTop: 20, borderTop: `1px solid ${C.border}` }}><h3 style={{ fontSize: 16, fontWeight: 500, margin: 0 }}>{column.title}</h3><ul style={{ display: "grid", gap: 14, padding: 0, margin: "24px 0 0", listStyle: "none" }}>{column.items.map(item => <li key={item} style={{ color: C.muted, lineHeight: 1.6, fontSize: 14, paddingLeft: 18, position: "relative" }}><span aria-hidden="true" style={{ position: "absolute", left: 0, top: 10, width: 5, height: 5, borderRadius: "50%", background: C.green }} />{item}</li>)}</ul></div>)}</div></section>; }
