'use client'

import Link from 'next/link'
import { useMemo, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { ArrowRightIcon, CheckCircleIcon, SparklesIcon } from '@heroicons/react/24/outline'
import { useSites } from '@/lib/hooks/useSites'

type FeedbackItem = { id: string; source: string; content: string; author_name: string | null; theme: string | null; sentiment: string | null; status: 'open' | 'reviewed' | 'archived'; created_at: string }
type CollectionSource = { id: string; site_id: string; type: string; active: boolean }
type Synthesis = { id: string; title: string; summary: string; themes: Array<{ name: string; count: number; insight: string; feedback_ids: string[] }>; recommendations: Array<{ title: string; action: string; rationale: string; priority: string; feedback_ids: string[] }>; created_at: string }
const sourceLabels: Record<string, string> = { manual: 'Ajout manuel', widget: 'Widget', public_link: 'Source externe', csv: 'Import CSV' }
async function getJson<T>(url: string) { const response = await fetch(url); if (!response.ok) throw new Error('Impossible de charger les données'); return response.json() as Promise<T> }

export function FeedbackDashboardOverview() {
  const { data: sites, isLoading: sitesLoading } = useSites()
  const activeSite = sites?.[0]
  const { data: feedback = [], isLoading, isError } = useQuery({ queryKey: ['feedback', activeSite?.id], queryFn: () => getJson<FeedbackItem[]>(`/api/feedback?siteId=${encodeURIComponent(activeSite!.id)}`), enabled: Boolean(activeSite?.id) })
  const { data: sources = [] } = useQuery({ queryKey: ['feedback-sources', activeSite?.id], queryFn: () => getJson<CollectionSource[]>('/api/feedback/sources'), enabled: Boolean(activeSite?.id) })
  const { data: syntheses = [] } = useQuery({ queryKey: ['feedback-syntheses', activeSite?.id], queryFn: () => getJson<Synthesis[]>(`/api/feedback/synthesis?siteId=${encodeURIComponent(activeSite!.id)}`), enabled: Boolean(activeSite?.id) })
  const [period, setPeriod] = useState<7 | 30 | 90>(7)
  const now = Date.now(); const currentSince = now - period * 86400000; const previousSince = now - period * 2 * 86400000
  const current = feedback.filter((item) => new Date(item.created_at).getTime() >= currentSince); const previous = feedback.filter((item) => { const time = new Date(item.created_at).getTime(); return time >= previousSince && time < currentSince })
  const newCount = feedback.filter((item) => item.status !== 'archived').length; const positiveRate = current.length ? Math.round((current.filter((item) => item.sentiment === 'positive').length / current.length) * 100) : 0
  const themes = useMemo(() => buildThemes(feedback, currentSince, previousSince), [feedback, currentSince, previousSince]); const topTheme = themes[0]; const pendingActions = syntheses[0]?.recommendations ?? []; const hasSource = sources.some((source) => source.site_id === activeSite?.id && source.active)
  const state = feedback.length === 0 ? 'empty' : feedback.length < 3 ? 'warming' : syntheses.length ? 'ready' : 'enough'; const projectLabel = sitesLoading ? 'Chargement du projet…' : activeSite?.name || activeSite?.url || 'Aucun projet'
  if (!activeSite && !sitesLoading) return <EmptyState title="Créez votre premier projet" body="Un projet rassemble vos sources, vos avis et les décisions qui en découlent." href="/onboarding" label="Créer un projet" />
  return <div className="space-y-7 pb-16">
    <header className="flex flex-col gap-5 border-b border-gray-200/80 pb-6 dark:border-white/[0.08] lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-3 flex flex-wrap items-center gap-2"><span className="inline-flex items-center gap-1.5 rounded-full border border-gray-200 bg-white px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.12em] text-gray-500 dark:border-white/[0.1] dark:bg-white/[0.04] dark:text-zinc-400"><span className={`h-1.5 w-1.5 rounded-full ${hasSource ? 'bg-emerald-500' : 'bg-gray-300 dark:bg-zinc-600'}`} />{hasSource ? 'Collecte active' : 'Collecte à configurer'}</span><span className="text-[11px] text-gray-400 dark:text-zinc-500">{projectLabel}</span></div><h1 className="max-w-3xl text-3xl font-semibold tracking-[-0.045em] text-gray-950 dark:text-white">{state === 'empty' ? 'Commencez à écouter vos clients.' : state === 'warming' ? `Encore ${3 - feedback.length} avis avant votre première synthèse.` : topTheme ? `${feedback.length} avis. “${topTheme.name}” mérite votre attention.` : `${feedback.length} avis structurés pour votre équipe.`}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-gray-500 dark:text-zinc-400">{state === 'empty' ? 'Installez le widget, importez un historique ou ajoutez un premier avis manuellement.' : topTheme ? `${topTheme.count} avis parlent de ce thème${pendingActions.length ? ` · ${pendingActions.length} recommandation${pendingActions.length > 1 ? 's' : ''} attend${pendingActions.length > 1 ? 'ent' : ''} votre décision` : ''}.` : 'Qualio rassemble les signaux utiles, les relie à leurs preuves et vous laisse décider.'}</p></div><div className="flex shrink-0 flex-wrap items-center gap-2"><div className="flex rounded-lg border border-gray-200 bg-white p-1 dark:border-white/[0.1] dark:bg-white/[0.04]">{([7, 30, 90] as const).map((value) => <button key={value} type="button" onClick={() => setPeriod(value)} className={`rounded-md px-2.5 py-1.5 text-xs font-semibold ${period === value ? 'bg-gray-950 text-white dark:bg-white dark:text-gray-950' : 'text-gray-500 hover:text-gray-900 dark:text-zinc-400 dark:hover:text-white'}`}>{value}j</button>)}</div><Link href={state === 'empty' || state === 'warming' ? '/dashboard/collection' : '/dashboard/actions'} className="inline-flex items-center gap-2 rounded-lg bg-[#ee6018] px-4 py-2.5 text-xs font-bold text-white shadow-sm shadow-[#ee6018]/20 transition hover:bg-[#d95514]">{state === 'empty' ? 'Configurer la collecte' : state === 'warming' ? 'Ajouter un avis' : 'Voir les actions'}<ArrowRightIcon className="h-4 w-4" /></Link></div></header>
    {isError ? <EmptyState title="Les avis sont indisponibles" body="Actualisez la page ou vérifiez la connexion de votre espace." href="/dashboard/collection" label="Vérifier la collecte" /> : <><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Nouveaux avis" value={String(newCount)} delta={delta(current.length, previous.length)} /><Metric label="Sentiment positif" value={current.length ? `${positiveRate} %` : '—'} delta={current.length && previous.length ? delta(positiveRate, Math.round((previous.filter((item) => item.sentiment === 'positive').length / previous.length) * 100), ' pts') : 'Pas encore de tendance'} /><Metric label="Thème principal" value={topTheme?.name ?? '—'} delta={topTheme ? `${topTheme.count} avis · ${topTheme.change}` : 'En attente des avis'} /><Metric label="Actions à décider" value={String(pendingActions.length)} delta={pendingActions.length ? 'Priorité équipe' : 'Aucune en attente'} emphasis={pendingActions.length > 0} /></section>{state === 'empty' ? <GettingStarted /> : <><section className="grid gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(300px,.75fr)]"><TrendPanel feedback={feedback} period={period} /><ActionPanel actions={pendingActions} /></section><section className="grid gap-5 xl:grid-cols-[minmax(0,1.2fr)_minmax(300px,.8fr)]"><ThemePanel themes={themes} /><RecentFeedback feedback={feedback} isLoading={isLoading} /></section></>}</>}
  </div>
}

function buildThemes(items: FeedbackItem[], since: number, previousSince: number) { const names = Array.from(new Set(items.map((item) => item.theme).filter((theme): theme is string => Boolean(theme)))); return names.map((name) => { const current = items.filter((item) => item.theme === name && new Date(item.created_at).getTime() >= since); const previous = items.filter((item) => { const time = new Date(item.created_at).getTime(); return item.theme === name && time >= previousSince && time < since }); const change = current.length - previous.length; return { name, count: current.length, change: change > 0 ? `↑ ${change}` : change < 0 ? `↓ ${Math.abs(change)}` : '—', tone: change > 0 ? 'up' : change < 0 ? 'down' : 'flat', quote: current[0]?.content ?? items.find((item) => item.theme === name)?.content ?? '' } }).sort((a, b) => b.count - a.count) }
function delta(current: number, previous: number, suffix = '') { if (!previous) return current ? 'Nouveau sur la période' : 'Pas encore de tendance'; const change = current - previous; return `${change > 0 ? '↑' : change < 0 ? '↓' : '—'} ${Math.abs(change)}${suffix} vs période précédente` }
function Metric({ label, value, delta: valueDelta, emphasis = false }: { label: string; value: string; delta: string; emphasis?: boolean }) { return <div className={`rounded-xl border p-4 ${emphasis ? 'border-orange-200 bg-orange-50/60 dark:border-orange-500/20 dark:bg-orange-500/[0.08]' : 'border-gray-200/80 bg-white dark:border-white/[0.08] dark:bg-[#181B21]'}`}><span className="block text-xs text-gray-500 dark:text-zinc-500">{label}</span><strong className="mt-3 block truncate text-2xl font-semibold tracking-[-0.05em] text-gray-950 dark:text-white">{value}</strong><span className={`mt-2 block text-[10px] font-medium ${emphasis ? 'text-[#c95720]' : 'text-gray-500 dark:text-zinc-500'}`}>{valueDelta}</span></div> }
function TrendPanel({ feedback, period }: { feedback: FeedbackItem[]; period: number }) { const buckets = Array.from({ length: 7 }, (_, index) => feedback.filter((item) => { const time = new Date(item.created_at).getTime(); const end = Date.now() - (6 - index) * period * 86400000 / 7; const start = end - period * 86400000 / 7; return time >= start && time < end }).length); const max = Math.max(...buckets, 1); return <section className="rounded-xl border border-gray-200/80 bg-white p-5 dark:border-white/[0.08] dark:bg-[#181B21]"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#ee6018]">Évolution</p><h2 className="mt-1 text-base font-semibold text-gray-950 dark:text-white">Volume des avis</h2><p className="mt-1 text-xs text-gray-500 dark:text-zinc-400">Sur les {period} derniers jours</p></div><span className="rounded-md bg-gray-50 px-2 py-1 text-[10px] font-semibold text-gray-500 dark:bg-white/[0.05] dark:text-zinc-400">{feedback.length} au total</span></div><div className="mt-7 flex h-36 items-end gap-2 border-b border-gray-100 dark:border-white/[0.06]">{buckets.map((count, index) => <div key={index} className="group flex flex-1 flex-col items-center justify-end gap-2"><span className="text-[10px] text-gray-400 opacity-0 transition group-hover:opacity-100">{count}</span><div className="w-full rounded-t-md bg-[#ee6018]/80 transition group-hover:bg-[#ee6018]" style={{ height: `${Math.max((count / max) * 100, count ? 8 : 2)}%` }} /></div>)}</div><div className="mt-2 flex justify-between text-[10px] text-gray-400"><span>Début</span><span>Aujourd’hui</span></div></section> }
function ThemePanel({ themes }: { themes: ReturnType<typeof buildThemes> }) { return <section className="rounded-xl border border-gray-200/80 bg-white dark:border-white/[0.08] dark:bg-[#181B21]"><div className="flex items-center justify-between border-b border-gray-100 px-5 py-4 dark:border-white/[0.06]"><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#ee6018]">Thèmes</p><h2 className="mt-1 text-base font-semibold text-gray-950 dark:text-white">Ce que vos clients répètent</h2></div><Link href="/dashboard/themes" className="text-xs font-bold text-[#c95720]">Voir tout <ArrowRightIcon className="ml-1 inline h-3.5 w-3.5" /></Link></div>{themes.length ? <div className="divide-y divide-gray-100 dark:divide-white/[0.06]">{themes.slice(0, 5).map((theme) => <Link href="/dashboard/themes" key={theme.name} className="flex items-start gap-3 px-5 py-4 transition hover:bg-gray-50 dark:hover:bg-white/[0.025]"><div className="mt-1 flex h-7 w-7 shrink-0 items-center justify-center rounded-md bg-orange-50 text-[10px] font-bold text-[#c95720] dark:bg-orange-500/10 dark:text-orange-300">{theme.count}</div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-semibold text-gray-900 dark:text-white">{theme.name}</h3><span className={`text-[10px] font-bold ${theme.tone === 'up' ? 'text-orange-600' : theme.tone === 'down' ? 'text-emerald-600' : 'text-gray-400'}`}>{theme.change}</span></div><p className="mt-1 line-clamp-1 text-xs text-gray-500 dark:text-zinc-400">“{theme.quote}”</p></div></Link>)}</div> : <div className="p-5 text-sm text-gray-500 dark:text-zinc-400">Les thèmes apparaîtront automatiquement avec les nouveaux avis.</div>}</section> }
function ActionPanel({ actions }: { actions: Synthesis['recommendations'] }) { return <section className="rounded-xl border border-orange-200/80 bg-[#fffaf6] p-5 dark:border-orange-500/20 dark:bg-orange-500/[0.06]"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#c95720]">À décider</p><h2 className="mt-1 text-base font-semibold text-gray-950 dark:text-white">Recommandations sourcées</h2></div><SparklesIcon className="h-5 w-5 text-[#ee6018]" /></div>{actions.length ? <div className="mt-4 space-y-3">{actions.slice(0, 3).map((action) => <Link href="/dashboard/actions" key={action.title} className="block rounded-lg border border-orange-200/70 bg-white p-3 transition hover:border-[#ee6018] dark:border-white/[0.08] dark:bg-[#181B21]"><div className="flex items-center justify-between gap-2"><h3 className="text-sm font-semibold text-gray-900 dark:text-white">{action.title}</h3><span className="text-[9px] font-bold uppercase tracking-[0.1em] text-[#c95720]">{action.priority}</span></div><p className="mt-1 line-clamp-2 text-xs leading-5 text-gray-500 dark:text-zinc-400">{action.action}</p></Link>)}</div> : <div className="mt-4 rounded-lg border border-dashed border-orange-200 p-4 text-sm text-gray-600 dark:border-orange-500/20 dark:text-zinc-400">Une recommandation apparaîtra ici après la première synthèse.</div>}<Link href="/dashboard/actions" className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-[#c95720]">Ouvrir les actions <ArrowRightIcon className="h-3.5 w-3.5" /></Link></section> }
function RecentFeedback({ feedback, isLoading }: { feedback: FeedbackItem[]; isLoading: boolean }) { return <section className="rounded-xl border border-gray-200/80 bg-white dark:border-white/[0.08] dark:bg-[#181B21]"><div className="flex items-center justify-between border-b border-gray-100 px-5 py-4 dark:border-white/[0.06]"><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#ee6018]">Derniers avis</p><h2 className="mt-1 text-base font-semibold text-gray-950 dark:text-white">Le signal récent</h2></div><Link href="/dashboard/feedback" className="text-xs font-bold text-[#c95720]">Voir tout <ArrowRightIcon className="ml-1 inline h-3.5 w-3.5" /></Link></div>{isLoading ? <p className="p-5 text-sm text-gray-500">Chargement…</p> : feedback.length ? <div className="divide-y divide-gray-100 dark:divide-white/[0.06]">{feedback.slice(0, 4).map((item) => <Link href="/dashboard/feedback" key={item.id} className="flex gap-3 px-5 py-3.5 transition hover:bg-gray-50 dark:hover:bg-white/[0.025]"><span className={`mt-1.5 h-2 w-2 shrink-0 rounded-full ${item.status === 'archived' ? 'bg-gray-300' : 'bg-[#ee6018]'}`} /><span className="min-w-0 flex-1"><span className="block line-clamp-2 text-sm leading-5 text-gray-800 dark:text-zinc-200">{item.content}</span><span className="mt-1 block text-[10px] text-gray-400">{sourceLabels[item.source] ?? item.source} · {item.theme ?? 'Thème en cours d’identification'}</span></span></Link>)}</div> : <p className="p-5 text-sm text-gray-500 dark:text-zinc-400">Aucun avis reçu pour le moment.</p>}</section> }
function GettingStarted() { return <section className="rounded-xl border border-dashed border-gray-300 bg-gray-50 p-6 dark:border-white/[0.12] dark:bg-white/[0.03]"><div className="flex items-start gap-3"><CheckCircleIcon className="mt-0.5 h-5 w-5 text-[#ee6018]" /><div><h2 className="text-base font-semibold text-gray-950 dark:text-white">Votre espace est prêt à écouter.</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-gray-500 dark:text-zinc-400">Choisissez le chemin le plus simple pour commencer. Vous pourrez compléter la collecte plus tard.</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><Link href="/dashboard/collection" className="rounded-lg border border-gray-200 bg-white p-4 transition hover:border-[#ee6018] dark:border-white/[0.1] dark:bg-[#181B21]"><strong className="block text-sm text-gray-900 dark:text-white">Installer le widget</strong><span className="mt-1 block text-xs leading-5 text-gray-500">Recevoir les prochains avis.</span></Link><Link href="/dashboard/collection" className="rounded-lg border border-gray-200 bg-white p-4 transition hover:border-[#ee6018] dark:border-white/[0.1] dark:bg-[#181B21]"><strong className="block text-sm text-gray-900 dark:text-white">Importer un CSV</strong><span className="mt-1 block text-xs leading-5 text-gray-500">Retrouver votre historique.</span></Link><Link href="/dashboard/collection" className="rounded-lg border border-gray-200 bg-white p-4 transition hover:border-[#ee6018] dark:border-white/[0.1] dark:bg-[#181B21]"><strong className="block text-sm text-gray-900 dark:text-white">Ajouter un avis</strong><span className="mt-1 block text-xs leading-5 text-gray-500">Tester le parcours manuellement.</span></Link></div></div></div></section> }
function EmptyState({ title, body, href, label }: { title: string; body: string; href: string; label: string }) { return <div className="mx-auto max-w-2xl rounded-xl border border-dashed border-gray-300 bg-gray-50 p-8 dark:border-white/10 dark:bg-white/[0.03]"><h1 className="text-xl font-semibold text-gray-900 dark:text-white">{title}</h1><p className="mt-2 text-sm leading-6 text-gray-500 dark:text-zinc-400">{body}</p><Link href={href} className="mt-5 inline-flex rounded-lg bg-[#ee6018] px-4 py-2.5 text-xs font-bold text-white">{label}</Link></div> }
