'use client'
import Link from 'next/link'
import { ArrowPathIcon, CheckCircleIcon, ExclamationTriangleIcon } from '@heroicons/react/24/outline'
import { useScanResults, useScanStatus } from '@/lib/hooks/useScan'
interface ScanProgressPanelProps { scanId: string; variant?: 'full' | 'compact' }
const STEPS = [{ statuses: ['queued'], label: 'Audit placé dans la file', detail: 'Qualio prépare la vérification des formulaires.' }, { statuses: ['running', 'discovering'], label: 'Ouverture du site', detail: 'Qualio ouvre le site dans un vrai navigateur.' }, { statuses: ['crawling'], label: 'Repérage des formulaires', detail: 'Recherche des formulaires de connexion et de contact.' }, { statuses: ['browser_testing'], label: 'Vérification des champs', detail: 'Contrôle des champs requis et des boutons d’envoi.' }, { statuses: ['analyzing'], label: 'Lecture des résultats', detail: 'Regroupement des formulaires et des signaux observés.' }, { statuses: ['reporting'], label: 'Préparation du résultat', detail: 'Mise en forme des éléments à vérifier ensuite.' }, { statuses: ['completed'], label: 'Audit terminé', detail: 'Les formulaires repérés sont prêts à être consultés.' }]
const TERMINAL = ['completed', 'failed', 'partial', 'blocked']
function stepState(index: number, status: string, progress: number) { if (status === 'failed' || status === 'blocked') return index === STEPS.length - 1 ? 'failed' : index < Math.ceil(progress / 15) ? 'done' : 'pending'; if (status === 'completed') return 'done'; const current = STEPS.findIndex((step) => step.statuses.includes(status)); return index < current ? 'done' : index === current ? 'active' : 'pending' }
export function ScanProgressPanel({ scanId, variant = 'full' }: ScanProgressPanelProps) {
  const { data: scan, isLoading, isError } = useScanStatus(scanId); const { data: results } = useScanResults(scanId, scan?.status)
  if (isLoading) return <div className="py-8 text-center text-sm text-gray-500">Chargement du suivi du scan…</div>
  if (isError || !scan) return <div className="py-8 text-center text-sm text-red-500">Impossible de charger ce scan.</div>
  return <div className={variant === 'compact' ? 'space-y-4' : 'space-y-6'}><div className="flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#ee6018]">Suivi du scan</p><p className="mt-1 text-sm font-semibold text-gray-900 dark:text-white">{scan.status === 'completed' ? 'Votre rapport est prêt' : scan.status === 'failed' || scan.status === 'blocked' ? 'Le scan a rencontré un problème' : 'Qualio travaille sur votre site'}</p></div><p className="text-2xl font-bold tabular-nums text-gray-900 dark:text-white">{scan.progress}%</p></div><div className="h-2 overflow-hidden rounded-full bg-gray-100"><div className="h-full rounded-full bg-[#ee6018] transition-all duration-700" style={{ width: `${scan.progress}%` }} /></div><div className="space-y-1">{STEPS.map((step, index) => { const state = stepState(index, scan.status, scan.progress); return <div key={step.label} className="flex gap-3 rounded-xl px-2 py-2"><div className={`mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-full ${state === 'done' ? 'bg-emerald-100 text-emerald-600' : state === 'active' ? 'bg-orange-100 text-[#ee6018]' : state === 'failed' ? 'bg-red-100 text-red-600' : 'bg-gray-100 text-gray-400'}`}>{state === 'done' ? <CheckCircleIcon className="h-4 w-4" /> : state === 'active' ? <ArrowPathIcon className="h-4 w-4 animate-spin" /> : state === 'failed' ? <ExclamationTriangleIcon className="h-4 w-4" /> : <span className="text-xs font-bold">{index + 1}</span>}</div><div><p className="text-sm font-semibold text-gray-800 dark:text-zinc-200">{step.label}</p><p className="text-xs text-gray-500">{step.detail}</p></div></div> })}</div>{scan.error && <div className="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700">{scan.error}</div>}{TERMINAL.includes(scan.status) && results && <div className="border-t border-gray-200 pt-4"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-sm font-bold">Résultat du scan</h2><span className="rounded-full border px-2.5 py-1 text-[11px] font-semibold">{scan.aiStatus === 'success' ? `Analyse IA · ${scan.aiCallsCount ?? 0} diagnostic(s)` : scan.aiStatus === 'failed' ? 'Analyse IA indisponible · résumé automatique' : 'Résumé automatique · aucun diagnostic nécessaire'}</span></div><p className="mt-2 text-xs text-gray-500">{results.issues.length} incident(s), {results.checks.length} contrôle(s) et {results.pages.length} page(s) enregistrés.</p>{variant === 'full' && <Link href="/dashboard/scans" className="mt-3 inline-flex rounded-lg bg-[#ee6018] px-4 py-2 text-xs font-semibold text-white">Voir l’historique</Link>}</div>}</div>
}
